DROP TABLE people IF EXISTS;

CREATE TABLE people
(
  ID                     bigint            NOT NULL,
  CONTRACT_NBR           longvarchar(30),
  BATCH_ID               bigint,
  BUSINESS_ID            bigint,
  RETURN_CODE            longvarchar(7),
  DD_FLAG                integer    DEFAULT 1,
  DD_FLAG_BATCH          longvarchar(20) DEFAULT 1,
  GC_TYPE                longvarchar(3),
  AMOUNT                 bigint,
  DD_REQ_SN              longvarchar(2),
  DEAL_INFO              longvarchar(32),
  PAYER_BANK_CODE        longvarchar(12),
  PAYER_BANK_REGIN_CODE  longvarchar(6),
  PAYER_BANK_NAME        longvarchar(100),
  PAYER_ACC_TYPE         longvarchar(2),
  PAYER_ACC_COMPANY_TYPE longvarchar(1),
  PAYER_ACC_NO           longvarchar(30),
  PAYER_ACC_NAME         longvarchar(50),
  PAYER_ID_CARD_TYPE     longvarchar(1),
  PAYER_ID_CARD_NO       longvarchar(30),
  CURRENCY_TYPE          longvarchar(3),
  DD_SIGN                longvarchar(1),
  TRANS_SN               longvarchar(32),
  REMARK                 longvarchar(30),
  SYS_REF_CODE           longvarchar(16),
  RESULT_INFO            longvarchar(100),
  SOURCE_ROW_IDX         bigint,
  ACC_BANK_CODE          longvarchar(30),
  ID_CATEGORY            integer DEFAULT 1   NOT NULL,
  PAIRED_TO_DD_REQUEST   integer DEFAULT 1   NOT NULL,
  ID_DD_REQ              bigint DEFAULT -1 NOT NULL
);
